# Generated by Django 4.1.7 on 2023-08-19 13:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("network", "0002_user_followers_post_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="edited",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="post",
            name="date_posted",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
