# Generated by Django 4.1.7 on 2023-08-19 13:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("network", "0003_post_edited_alter_post_date_posted"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="edited_on",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="date_posted",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
